### ISSUE TITLE
[ROS 2] ROS_PACKAGE_PATH and ROS_ETC_DIR

### ISSUE THREAD

**Issue by seanyen** [ros/ros_environment#25]
On ROS 1, `rosdep` consumes the following to complete its task:
*  `ROS_PACKAGE_PATH`: `rosdep` uses it to figure out what's the ROS package keys in current sourced environment.
*  `ROS_ETC_DIR`: `rosdep` uses it to figure out where `rosdep\sources.list.d` is and later read the `rosdep` mapping files.

On ROS 2, do we expect the similar model? Currently those are not exported by `ROS 2` but only for `ROS 1` right?

**Comment by dirk-thomas** [comment]
> Currently those are not exported by ROS 2 but only for ROS 1 right?

Correct.

> do we expect the similar model?

The closest equivalent to `ROS_PACKAGE_PATH` is `AMENT_PREFIX_PATH`.

The is no equivalent to `ROS_ETC_DIR` in ROS 2.

This would be up to `rosdep` to determine how to handle it.

Since there is nothing to be done in this repository I will go ahead and close this ticket. Please feel free to follow up with a ticket in the [rosdep](https://github.com/ros-infrastructure/rosdep/) repo.
